branches:
  only:
  - master
language: python
python:
- '3.4'
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}"
  == "false" ]; then pip install pygithub; pip install pygithub3; fi
script:
- python3 tools/sqf_validator.py
- python3 tools/config_style_checker.py
notifications:
  slack:
    rooms:
      - secure: UkMypUQjMZojv1owOjzONX8nQupRbA7J99v5G7duRJacrIrfNM6xRYchKnP8PRWoWBvS+zmxT1bZcP3kgwuUbV9KfXMpgFgeUqQZe3RASEomN5Rvb1lNkVYxYXbe3KCX5IIymWNlqMYDskSxcZdP36uBSQVStSDIJR1ykNdpzRDkurVJWSZXBP+gdyU6kQVl3yWVSpkn2XRzysYglbKZHkpbr4gBoMx/yDk5ZxypsLiD3XuTWiqY8YNaWGeB3g6wGW6Z2YY35rzI19VEQSiUpZjCH7TpRdyki/kyEosvlHlaeBPNVRIAbnYcRlp6D3T3VWBu8GzDUtMSsCiIkOMp7DHlR2yhSSMW9HY77sWGzO9h4ut3uBGpaSCQobsMRwCXO5kwVVtr7jtSpwzXcVChQyWvfLDdeG0JqPfxDzD72kSFbfW0faNPaKd4ubJCnK7Z7q37KzIT7Sf33cymAUXtgrMna/J/HJO57tswqoOfQI9R1ZimwhXmgFHcW2dvrxCAcHUdm+n7cEoGxUgCHx+YNW8pTI98H94xlV8QOajjMRa6T5e6+GA4bSQ2mf6Yho0Q/wW9lTANp3mT3e0tfXHC2TocXldnbUtT5bMssEFD373DnkBgTLEmDhNZKN/dtnVIQaDXkcQS7GjFaD0a99anxGpLk/Iy2fQWVDmKT9E0nSI=
    on_success: never
    on_failure: always
